INSERT INTO component_statuses(description)
VALUES 
    ("Inactive"),
    ("Active");

INSERT INTO component_types(description) VALUES
    ('1Password Group'),
    ('1Password User'),
    ('1Password Vault'),
    ('1Password Vault Item'),
    ('Active Campaign Automation'),
    ('Airtable API'),
    ('Airtable Automation'),
    ('Airtable Base'),
    ('Airtable Base Extension'),
    ('Airtable Base Form'),
    ('Airtable Base Interface'),
    ('Airtable Base Table'),
    ('Asana API'),
    ('Asana Project'),
    ('Asana Project Form'),
    ('Asana Project Template'),
    ('Asana Task'),
    ('Asana Task Template'),
    ('Asana User'),
    ('Calendly Calendar'),
    ('Calendly User'),
    ('Chrome Extension'),
    ('ConvertCalculator Calculator'),
    ('Document360 Document'),
    ('DocuSign Template'),
    ('GitHub Repository'),
    ('Google Apps Script'),
    ('Google Workspace Calendar'),
    ('Google Workspace Doc'),
    ('Google Workspace Drive Folder'),
    ('Google Workspace Group'),
    ('Google Workspace Sheet'),
    ('Google Workspace Sheet Tab'),
    ('Google Workspace User'),
    ('HubSpot Company'),
    ('HubSpot Contact'),
    ('HubSpot Deal Pipeline'),
    ('HubSpot Sequence'),
    ('HubSpot User'),
    ('HubSpot Workflow'),
    ('Jotform API'),
    ('Jotform Form'),
    ('Jotform Form Email'),
    ('Jotform Submissions Table'),
    ('Mailchimp Audience'),
    ('Mailchimp Campaign'),
    ('Miro Diagram'),
    ('Pandadoc Template'),
    ('PythonAnywhere Script'),
    ('Render Background Worker'),
    ('Render Cron Job'),
    ('Render Static Site'),
    ('Slack Channel'),
    ('Slack User'),
    ('Slack User Group'),
    ('Vidyard User'),
    ('Vidyard Video'),
    ('Zapier Folder'),
    ('Zapier Zap');
