CREATE TABLE IF NOT EXISTS billing_frequencies (
  id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  description VARCHAR(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS cost_audit_frequencies (
  id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  description VARCHAR(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS payment_methods (
  id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  issuing_bank VARCHAR(30) NOT NULL,
  card_holder_name VARCHAR(100) NOT NULL,
  last_four_digits INT NOT NULL
);