CREATE TABLE IF NOT EXISTS component_statuses (
  id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  description VARCHAR(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS component_types (
  id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  description VARCHAR(50) NOT NULL
);