CREATE TABLE IF NOT EXISTS system_team_choices (
  id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  description VARCHAR(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS system_statuses (
  id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  description VARCHAR(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS system_audit_statuses (
  id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  description VARCHAR(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS system_audit_frequencies (
  id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  description VARCHAR(30) NOT NULL
);