CREATE IF NOT EXISTS TABLE ticket_priorities (
  id INT PRIMARY KEY AUTOINCREMENT NOT NULL,
  description VARCHAR(30) NOT NULL
);

CREATE IF NOT EXISTS TABLE ticket_tiers (
  id INT PRIMARY KEY AUTOINCREMENT NOT NULL,
  description VARCHAR(30) NOT NULL,
  points INT NOT NULL
);

CREATE IF NOT EXISTS TABLE ticket_entity_choices (
  id INT PRIMARY KEY AUTOINCREMENT NOT NULL,
  description VARCHAR(30) NOT NULL
);

CREATE IF NOT EXISTS TABLE ticket_access_approvals (
  id INT PRIMARY KEY AUTOINCREMENT NOT NULL,
  description VARCHAR(30) NOT NULL
);

CREATE IF NOT EXISTS TABLE ticket_statuses (
  id INT PRIMARY KEY AUTOINCREMENT NOT NULL,
  description VARCHAR(30) NOT NULL
);

CREATE IF NOT EXISTS TABLE ticket_change_approvals (
  id INT PRIMARY KEY AUTOINCREMENT NOT NULL,
  description VARCHAR(30) NOT NULL
);

CREATE IF NOT EXISTS TABLE ticket_types (
  id INT PRIMARY KEY AUTOINCREMENT NOT NULL,
  description VARCHAR(30) NOT NULL
);