CREATE TABLE IF NOT EXISTS ticket_priorities (
  id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  description VARCHAR(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS ticket_tiers (
  id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  description VARCHAR(30) NOT NULL,
  points INT NOT NULL
);

CREATE TABLE IF NOT EXISTS ticket_entity_choices (
  id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  description VARCHAR(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS ticket_access_approvals (
  id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  description VARCHAR(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS ticket_statuses (
  id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  description VARCHAR(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS ticket_change_approvals (
  id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  description VARCHAR(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS ticket_types (
  id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  description VARCHAR(30) NOT NULL
);